version: '3.1'
services:
  testdashboard:
    build: '.'
    environment:
      ENV: "PRODUCTION"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: 0
      STREAMLIT_CLIENT_SHOW_ERROR_DETAILS: 0
      ENGINE_BASE_URL: "http://faker:3030"
      ENGINE_AUTH: ${ENGINE_AUTH}
      MINIO_HOST: "minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SECURE: 0
    ports:
      - "8501:8501"
    depends_on:
      faker:
        condition: service_healthy
      minio:
        condition: service_healthy
  
  faker:
    image: dotronglong/faker:stable
    volumes:
      - ./dashboard/tests/mocks:/app/mocks
    ports:
      - "3002:3030"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget 'http://localhost:3030/healthcheck' -O /dev/null || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 1s
      timeout: 3s
      retries: 30
