version: '3.1'

services:
  dashboard:
    build:
      content: '.''
    #    image: bingneef/rekenkamer-report-dashboard:0.0.1
    restart: always
    ports:
      - "80:8501"
    environment:
      ENV: "PRODUCTION"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
      STREAMLIT_CLIENT_SHOW_ERROR_DETAILS: false
      ENGINE_BASE_URL: "_"
      ENGINE_AUTH: "_"
      MINIO_HOST: "localhost:9000"
      MINIO_ACCESS_KEY: "_"
      MINIO_SECRET_KEY: "_"
      MINIO_SECURE: 0
