# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install --no-root --with dev
      - name: Install Playwright
        run: |
          python3 playwright install
          python3 playwright install-deps
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python3 flake8 dashboard --count --show-source --statistics
      - name: Test with pytest
        run: |
          docker-compose -f docker-compose.test.yml up -d
          python3 pytest --cov
      #- name: Verify screenshots
      #  run: |
      #    # Check if screenshots were unaltered
      #    if [[ $(git status --porcelain dashboard) ]]; then
      #      git status --porcelain dashboard
      #      echo "Playwright tests failed."
      #      exit 1
      #    else
      #      echo "Playwright tests passed."
      #      exit 0
      #    fi
