CUSTOM_SOURCES_MAIN_SEARCH = ""

TRACKING_ENABLE = 0
TRACKING_DOMAIN = ""
TRACKING_HOST = ""

ENGINE_BASE_URL = "http://localhost:3002"
ENGINE_AUTH = "private-xx"

MINIO_HOST = "localhost:9000"
MINIO_ACCESS_KEY = ""
MINIO_SECRET_KEY = ""
MINIO_SECURE = 0